name: Deploy to monday code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to monday code
        uses: mondaycom/monday-code-deploy-action@v3
        with:
          token: ${{ secrets.MONDAY_TOKEN }}
          appId: ${{ secrets.MONDAY_APP_ID }}
          force: true
